DROP TABLE "JOAO"."registro_status" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."localidade" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."aruco_tag" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."moto" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."camera" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."funcionario" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."patio" CASCADE CONSTRAINTS;
DROP TABLE "JOAO"."__EFMigrationsHistory" CASCADE CONSTRAINTS;
